# Generated by Django 2.1.2 on 2018-12-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobileno', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=6)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
