# Generated by Django 2.1.2 on 2018-12-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=4, max_length=50),
            preserve_default=False,
        ),
    ]
