# Generated by Django 2.1.2 on 2018-12-26 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Upbhokta',
        ),
    ]
