# Generated by Django 2.1.2 on 2018-12-26 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20181226_1327'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Upbhokta',
            new_name='User',
        ),
    ]
