# Generated by Django 2.1.2 on 2018-12-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20181226_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AlterField(
            model_name='user',
            name='mobileno',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
